"""initial schema

Revision ID: d02740717c5a
Revises: 
Create Date: 2026-02-26 20:25:29.787434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02740717c5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('escalation_reason', sa.String(length=255), nullable=True),
    sa.Column('escalation_metadata', sa.JSON(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_sessions_agent_id'), 'escalation_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_escalation_sessions_conversation_id'), 'escalation_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_escalation_sessions_session_id'), 'escalation_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_escalation_sessions_user_id'), 'escalation_sessions', ['user_id'], unique=False)
    op.create_table('motor_private_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cover_type', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('vehicle_make', sa.String(length=50), nullable=False),
    sa.Column('year_of_manufacture', sa.String(length=4), nullable=False),
    sa.Column('cover_start_date', sa.String(length=20), nullable=False),
    sa.Column('is_rare_model', sa.String(length=8), nullable=False),
    sa.Column('has_undergone_valuation', sa.String(length=8), nullable=False),
    sa.Column('vehicle_value_ugx', sa.Float(), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motor_private_applications_user_id'), 'motor_private_applications', ['user_id'], unique=False)
    op.create_table('personal_accident_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('personal_details', sa.JSON(), nullable=False),
    sa.Column('next_of_kin', sa.JSON(), nullable=False),
    sa.Column('previous_pa_policy', sa.JSON(), nullable=False),
    sa.Column('physical_disability', sa.JSON(), nullable=False),
    sa.Column('risky_activities', sa.JSON(), nullable=False),
    sa.Column('coverage_plan', sa.JSON(), nullable=False),
    sa.Column('national_id_upload', sa.JSON(), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_accident_applications_user_id'), 'personal_accident_applications', ['user_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=256), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('premium_amount', sa.Float(), nullable=False),
    sa.Column('sum_assured', sa.Float(), nullable=True),
    sa.Column('underwriting_data', sa.JSON(), nullable=False),
    sa.Column('pricing_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_table('serenicare_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('main_members', sa.JSON(), nullable=False),
    sa.Column('cover_personalization', sa.JSON(), nullable=False),
    sa.Column('optional_benefits', sa.JSON(), nullable=False),
    sa.Column('medical_conditions', sa.JSON(), nullable=False),
    sa.Column('plan_option', sa.JSON(), nullable=False),
    sa.Column('about_you', sa.JSON(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('plan_type', sa.String(length=32), nullable=True),
    sa.Column('serious_conditions', sa.String(length=8), nullable=True),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serenicare_applications_user_id'), 'serenicare_applications', ['user_id'], unique=False)
    op.create_table('travel_insurance_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('selected_product', sa.JSON(), nullable=False),
    sa.Column('about_you', sa.JSON(), nullable=False),
    sa.Column('travel_party_and_trip', sa.JSON(), nullable=False),
    sa.Column('data_consent', sa.JSON(), nullable=False),
    sa.Column('travellers', sa.JSON(), nullable=False),
    sa.Column('emergency_contact', sa.JSON(), nullable=False),
    sa.Column('bank_details', sa.JSON(), nullable=False),
    sa.Column('passport_upload', sa.JSON(), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_insurance_applications_user_id'), 'travel_insurance_applications', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('kyc_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_travel_insurance_applications_user_id'), table_name='travel_insurance_applications')
    op.drop_table('travel_insurance_applications')
    op.drop_index(op.f('ix_serenicare_applications_user_id'), table_name='serenicare_applications')
    op.drop_table('serenicare_applications')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_personal_accident_applications_user_id'), table_name='personal_accident_applications')
    op.drop_table('personal_accident_applications')
    op.drop_index(op.f('ix_motor_private_applications_user_id'), table_name='motor_private_applications')
    op.drop_table('motor_private_applications')
    op.drop_index(op.f('ix_escalation_sessions_user_id'), table_name='escalation_sessions')
    op.drop_index(op.f('ix_escalation_sessions_session_id'), table_name='escalation_sessions')
    op.drop_index(op.f('ix_escalation_sessions_conversation_id'), table_name='escalation_sessions')
    op.drop_index(op.f('ix_escalation_sessions_agent_id'), table_name='escalation_sessions')
    op.drop_table('escalation_sessions')
    # ### end Alembic commands ###
